[package]
org = "smartrelief"
name = "donor_management_service"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.3"

